// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8vE6gdQhQ_Q5LcpwG1-VWyCXrwOmsx8U',
    appId: '1:809251756287:android:e9f86c3b4afc80373f94ca',
    messagingSenderId: '809251756287',
    projectId: 'framework-ecommerce-eeb5d',
    storageBucket: 'framework-ecommerce-eeb5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8fTHK_akemDpMSHhsqNSjalFTNYEBlo',
    appId: '1:809251756287:ios:c5430d190e462bf93f94ca',
    messagingSenderId: '809251756287',
    projectId: 'framework-ecommerce-eeb5d',
    storageBucket: 'framework-ecommerce-eeb5d.appspot.com',
    iosClientId: '809251756287-5n6mu0rebkv0r09a9h9bicmgq8eu565p.apps.googleusercontent.com',
    iosBundleId: 'com.jacielmelnik.framework',
  );
}
